### ISSUE TITLE
Script/function to import data from legacy IT Assets system

### ISSUE THREAD

**Issue by ropable** [parksandwildlife/oim-cms#227]
Legacy IT Assets system: https://assets.dpaw.wa.gov.au/admin/
Legacy project repo: https://github.com/parksandwildlife/it-assets

Create a utility script in the assets app (assets/utils.py) to import data from the old system into the CMS. Easiest way would be to assume that the data is available as dumped, serialised fixtures.

Model map (old -> new):

- Supplier -> Vendor
- Model -> HardwareModel
- Location -> Location
- Invoice -> Invoice
- Asset -> HardwareAsset

**Comment by xzzy** [comment]
One Off import script of data from Legacy Asset System to New Asset system in OIM-CMS.

**Script Task Requriments.** 
Task Steps
1. Export data from the follow tables. (json format) 
Supplier -> Vendor
Model -> HardwareModel
Location -> Location
Invoice -> Invoice
Asset -> HardwareAsset
2. Copy Export data across to new legacy system
3. Import data into new system match data into OIM table structure and column and accounting for the new tables foreign keys.

**Comment by xzzy** [comment]
Supplier -> Vendor: assets.models.Vendor
Model -> HardwareModel:  assets.models.HardwareModel
Location -> Location: organisation.models.Location
Invoice -> Invoice: assets.models.Invoice
Asset -> HardwareAsset: assets.model.HardwareAsset

**Comment by xzzy** [comment]
Hi Ashley, 

assets_locations = Legacy table
organisation_location = OIM location table 

The new data set for locations is completely different to the legacy .     The old legacy document has multiple area for the same locations.      We may need to adjust the locations in the new system or amend additional location fields to the asset table other wise potentially lose location information

[assets_locations.xlsx](https://github.com/parksandwildlife/oim-cms/files/561443/assets_locations.xlsx)
[organisation_location.xlsx](https://github.com/parksandwildlife/oim-cms/files/561444/organisation_location.xlsx)

**Comment by ropable** [comment]
@xzzy Look at SecondaryLocation model in the organisation model as an additional sublevel for location. We can also alter SecondaryLocation to add an additional "description" CharField to get a 3rd level of sub-location (with a unique_together constraint for (name, description).

Can you see if that works with the legacy data?

**Comment by xzzy** [comment]
Yeah was looking at the secondary location as well.     The ugly part tho is assets_location name, block,site field contains a combination of secondary and primary information.

The site field looks like it contains a combination of primary and secondary . 

eg the information that says rack 1, 2, 3, reception when this should probably be tertiary field as it a location with in a location.   

and than under site you have mobile communication facility which should probably be under block.  Also portable which should probably be its own (yes/no) field  .  Also portable should probably also be listing it home base location and than the option to show it portable asset.

My suggestion to ensure we don't lose important data.  

1. Add Portable yes/no to asset table
2. Manually create the equivalent location data in the new location structure and than create a manually ID map between which we can than code the import around.  Also the new location data has address and other information that isn't in the legacy system..    if you want to ensure the integrity of the data i think a manual approach may be best first up due to to many inconsistency with the data.  

Your thoughts?

![loc2](https://cloud.githubusercontent.com/assets/12062380/19877528/f925c870-a01a-11e6-8129-81a0f6f6af63.PNG)
![loc1](https://cloud.githubusercontent.com/assets/12062380/19877529/f929f4cc-a01a-11e6-8e73-dd756edb2e12.PNG)

**Comment by xzzy** [comment]
Another Question Ashley.  

The new vendor tables remove audit ability information is this by design?.   Also which content is meant to be populated into details and extra_data?

![supplier to vendors](https://cloud.githubusercontent.com/assets/12062380/19879608/7dfe9cac-a02f-11e6-839c-9ac042f14009.PNG)

**Comment by xzzy** [comment]
Same with assets_model to assets_hardwaremodel   removing the audit columns?

![model to hardwaremodel](https://cloud.githubusercontent.com/assets/12062380/19879740/fb4b614e-a030-11e6-8655-386a779982ff.PNG)

**Comment by xzzy** [comment]
Invoice audit columns removed and have 4 fields not match from old system and 3 fields in the new system not matched

![invoice to invoice](https://cloud.githubusercontent.com/assets/12062380/19879828/07c9a6fa-a032-11e6-9132-451b586cbc47.PNG)

**Comment by xzzy** [comment]
Asset table looks pretty good.  everything matches up mostly...  new table has some extra columns and is missing the audit columns.

![assets_asset to assets_hardwareasset](https://cloud.githubusercontent.com/assets/12062380/19879959/808066a0-a033-11e6-8ae6-183e423da72f.PNG)

**Comment by xzzy** [comment]
Spread sheet link of locations between new and old system

[assets_locations_no2.xlsx](https://github.com/parksandwildlife/oim-cms/files/565595/assets_locations_no2.xlsx)

**Comment by xzzy** [comment]
In the old asset system table 'assets_asset' the assigned_user was  a free text field.  With the new structure assigned user is and integer.   What should be done with the data that is not a valid user?

![image](https://cloud.githubusercontent.com/assets/12062380/19998313/20c203f6-a2a7-11e6-85b5-fb756a7697b0.png)

**Comment by ropable** [comment]
@xzzy Match on username if possible, otherwise leave assigned user blank.

**Comment by xzzy** [comment]
Sure,  will leave blank if no user match.  there some other data which doesn't look like a name ill place it into extra_data.  

here and interesting stat out of 1903 records in auth_user 1837 have a unique first / last name record.... hmm.  hope fully we get lucky with the right unique name match.

**Comment by xzzy** [comment]
arhh 47 are blank records.  still a few dupes or potential real people with the same name

![image](https://cloud.githubusercontent.com/assets/12062380/20000407/3ee9af22-a2b2-11e6-9374-9e06b2279dc1.png)

**Comment by xzzy** [comment]
This script is pretty much done.    We still need to finish off assets_locations_no2.xlsx Excel ID map. 

The script also inserts Unknown Vendor and Unknown Address rows into assets_vendor and organisation_location to get around the foreign key constraints.  Once the data has been fix with this information manual we can probably remove them.

I'm using direct SQL rather than the django object as it much easier to connect to 2 databases at the same time rather than having to setup a new django settings file.
